const PDFDocument = require("pdfkit");

/**
 * Generate a prescription PDF and pipe it to the Express response.
 * @param {Object} res         - Express response object
 * @param {Object} prescription - Prescription document (populated)
 */
function generatePrescriptionPDF(res, prescription) {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=prescription-${prescription._id}.pdf`
  );
  doc.pipe(res);

  /* ── Header ── */
  doc
    .fontSize(22)
    .font("Helvetica-Bold")
    .text("Baymaxify", { align: "center" })
    .fontSize(11)
    .font("Helvetica")
    .text("Mental Health Support Platform", { align: "center" })
    .moveDown(0.5);

  doc
    .moveTo(50, doc.y)
    .lineTo(562, doc.y)
    .strokeColor("#2255A4")
    .lineWidth(2)
    .stroke()
    .moveDown(0.8);

  /* ── Prescription ID + Date ── */
  const dateStr = new Date(prescription.createdAt).toLocaleDateString("en-IN", {
    day: "numeric", month: "long", year: "numeric",
  });

  doc
    .fontSize(10)
    .font("Helvetica")
    .fillColor("#666")
    .text(`Prescription ID: ${prescription._id}`, { continued: true })
    .text(`Date: ${dateStr}`, { align: "right" })
    .moveDown(1);

  /* ── Doctor & Patient ── */
  doc.fillColor("#000").fontSize(12).font("Helvetica-Bold").text("Doctor");
  doc
    .font("Helvetica")
    .fontSize(11)
    .text(`Name:      ${prescription.doctorId?.name || "N/A"}`)
    .text(`Specialty: ${prescription.doctorId?.specialty || "N/A"}`)
    .moveDown(0.8);

  doc.font("Helvetica-Bold").fontSize(12).text("Patient");
  doc
    .font("Helvetica")
    .fontSize(11)
    .text(`Name: ${prescription.userId?.name || "N/A"}`)
    .moveDown(0.8);

  /* ── Diagnosis ── */
  if (prescription.diagnosis) {
    doc.font("Helvetica-Bold").fontSize(12).text("Diagnosis");
    doc.font("Helvetica").fontSize(11).text(prescription.diagnosis).moveDown(0.8);
  }

  /* ── Medicines ── */
  doc
    .moveTo(50, doc.y)
    .lineTo(562, doc.y)
    .strokeColor("#ccc")
    .lineWidth(1)
    .stroke()
    .moveDown(0.5);

  doc.font("Helvetica-Bold").fontSize(12).text("Prescribed Medicines");
  doc.moveDown(0.4);

  prescription.medicines.forEach((med, idx) => {
    doc
      .font("Helvetica")
      .fontSize(11)
      .text(`${idx + 1}.  ${med.name}`, { continued: true })
      .text(`   ${med.frequency}   ×   ${med.days} days`, { align: "right" });
  });

  /* ── Remark ── */
  if (prescription.remark) {
    doc.moveDown(0.8);
    doc.font("Helvetica-Bold").fontSize(12).text("Doctor's Remark");
    doc
      .font("Helvetica")
      .fontSize(11)
      .fillColor("#333")
      .text(prescription.remark, { width: 460 });
  }

  /* ── Footer ── */
  doc
    .moveDown(2)
    .moveTo(50, doc.y)
    .lineTo(562, doc.y)
    .strokeColor("#ccc")
    .lineWidth(1)
    .stroke()
    .moveDown(0.5);

  doc
    .fontSize(9)
    .fillColor("#999")
    .text(
      "This prescription is generated by Baymaxify. For emergencies call iCall: 9152987821.",
      { align: "center" }
    );

  doc.end();
}

module.exports = generatePrescriptionPDF;